# Generated by Django 4.2.29 on 2026-03-12 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "authentication",
            "0003_projectaccess_project_projectaccess_user_user_groups_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the event",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("password_changed", "Password Changed"),
                            ("password_reset", "Password Reset"),
                            ("organization_created", "Organization Created"),
                            ("organization_updated", "Organization Updated"),
                            ("organization_deleted", "Organization Deleted"),
                            ("project_created", "Project Created"),
                            ("project_updated", "Project Updated"),
                            ("project_deleted", "Project Deleted"),
                            ("project_status_changed", "Project Status Changed"),
                            ("contract_created", "Contract Created"),
                            ("contract_updated", "Contract Updated"),
                            ("contract_signed", "Contract Signed"),
                            ("contract_terminated", "Contract Terminated"),
                            ("contract_variation_added", "Contract Variation Added"),
                            ("subcontract_created", "Subcontract Created"),
                            ("subcontract_updated", "Subcontract Updated"),
                            ("subcontract_approved", "Subcontract Approved"),
                            ("subcontract_rejected", "Subcontract Rejected"),
                            ("document_uploaded", "Document Uploaded"),
                            ("document_downloaded", "Document Downloaded"),
                            ("document_viewed", "Document Viewed"),
                            ("document_shared", "Document Shared"),
                            ("document_signed", "Document Signed"),
                            ("document_deleted", "Document Deleted"),
                            ("document_updated", "Document Updated"),
                            ("variation_created", "Variation Created"),
                            ("variation_submitted", "Variation Submitted"),
                            ("variation_approved", "Variation Approved"),
                            ("variation_rejected", "Variation Rejected"),
                            ("variation_withdrawn", "Variation Withdrawn"),
                            ("variation_revised", "Variation Revised"),
                            ("claim_created", "Claim Created"),
                            ("claim_submitted", "Claim Submitted"),
                            ("claim_certified", "Claim Certified"),
                            ("claim_rejected", "Claim Rejected"),
                            ("claim_revised", "Claim Revised"),
                            ("claim_paid", "Claim Paid"),
                            ("payment_created", "Payment Created"),
                            ("payment_recorded", "Payment Recorded"),
                            ("payment_approved", "Payment Approved"),
                            ("payment_processed", "Payment Processed"),
                            ("payment_reversed", "Payment Reversed"),
                            ("approval_requested", "Approval Requested"),
                            ("approval_granted", "Approval Granted"),
                            ("approval_denied", "Approval Denied"),
                            ("approval_delegated", "Approval Delegated"),
                            ("report_generated", "Report Generated"),
                            ("report_exported", "Report Exported"),
                            ("report_scheduled", "Report Scheduled"),
                            ("lpo_created", "LPO Created"),
                            ("lpo_approved", "LPO Approved"),
                            ("lpo_issued", "LPO Issued"),
                            ("lpo_received", "LPO Received"),
                            ("notification_sent", "Notification Sent"),
                            ("notification_read", "Notification Read"),
                            ("data_exported", "Data Exported"),
                            ("data_imported", "Data Imported"),
                            ("backup_created", "Backup Created"),
                            ("settings_changed", "Settings Changed"),
                            ("api_request", "API Request"),
                            ("api_error", "API Error"),
                        ],
                        db_index=True,
                        help_text="Type of event that occurred",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the entity this event relates to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the event occurred",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event data (context, changes, etc.)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which the event originated",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User agent string (for web requests)",
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Request path (for API events)",
                        max_length=500,
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTTP method (GET, POST, PUT, DELETE, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True, help_text="HTTP response status code", null=True
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Request duration in milliseconds (for performance tracking)",
                        null=True,
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of entity this event relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization context for this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="authentication.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project context for this event (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this event (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Event",
                "verbose_name_plural": "System Events",
                "db_table": "system_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="events_timestamp_idx"),
                    models.Index(
                        fields=["event_type", "-timestamp"], name="events_type_time_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"], name="events_user_time_idx"
                    ),
                    models.Index(
                        fields=["project", "-timestamp"], name="events_project_time_idx"
                    ),
                    models.Index(
                        fields=["organization", "-timestamp"],
                        name="events_org_time_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="events_entity_idx"
                    ),
                ],
            },
        ),
    ]
