# Generated by Django 4.2.29 on 2026-03-10 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique project code", max_length=50, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        help_text="Project owner/contractor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="projects_code_7205ea_idx"),
                    models.Index(
                        fields=["contractor", "status"],
                        name="projects_contrac_aa5fe9_idx",
                    ),
                ],
            },
        ),
    ]
