# Generated by custom migration for UUID conversion

from django.db import migrations, models
import django.db.models.deletion
import uuid


def clear_existing_projects(apps, schema_editor):
    """
    Clear existing projects before UUID conversion.
    This is safe for development/test environments.
    """
    Project = apps.get_model('projects', 'Project')
    Project.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0003_alter_organization_logo_alter_organization_name_and_more",
        ),
        ("projects", "0001_initial"),
    ]

    operations = [
        # Step 1: Clear existing data to avoid ID conversion issues
        migrations.RunPython(clear_existing_projects, migrations.RunPython.noop),
        
        # Step 2: Remove old index
        migrations.RemoveIndex(
            model_name="project",
            name="projects_contrac_aa5fe9_idx",
        ),
        
        # Step 3: Remove contractor field
        migrations.RemoveField(
            model_name="project",
            name="contractor",
        ),
        
        # Step 4: Create ProjectStage model
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PRELIMINARY", "Preliminary Works"),
                            ("SHELL", "Shell"),
                            ("FINISHES", "Finishes"),
                            ("EXTERNAL_WORKS", "External Works"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Stage sequence order"),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Stage",
                "verbose_name_plural": "Project Stages",
                "db_table": "project_stages",
                "ordering": ["project", "order"],
            },
        ),
        
        # Step 5: Add new fields to Project
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(blank=True, help_text="Client name", max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("LABOUR_ONLY", "Labour Only Contract"),
                    ("FULL_CONTRACT", "Full Contract"),
                ],
                default="FULL_CONTRACT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.TextField(blank=True, help_text="Project location"),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization owning this project",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("NEW_CONSTRUCTION", "New Construction"),
                    ("RENOVATION", "Renovation"),
                ],
                default="NEW_CONSTRUCTION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total project contract value",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        
        # Step 6: Alter existing fields
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(help_text="Unique project code", max_length=50),
        ),
        
        # Step 7: Convert ID to UUID (now safe because we cleared data)
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("DESIGN", "Design"),
                    ("APPROVAL", "Approval"),
                    ("IMPLEMENTATION", "Implementation"),
                    ("COMPLETED", "Completed"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DESIGN",
                max_length=20,
            ),
        ),
        
        # Step 8: Add ProjectStage foreign key to Project
        migrations.AddField(
            model_name="projectstage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="projects.project",
            ),
        ),
        
        # Step 9: Add constraints and indexes
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("organization", "code")},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "status"], name="projects_organiz_ca8931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["client_name"], name="projects_client__024960_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectstage",
            index=models.Index(
                fields=["project", "order"], name="project_sta_project_dbc8fd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectstage",
            unique_together={("project", "name")},
        ),
    ]
