# Generated by Django 4.2.29 on 2026-03-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_year_sequence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="project",
            new_name="projects_organiz_4857d7_idx",
            old_name="projects_organiz_0d3d43_idx",
        ),
    ]
