# Generated by Django 4.2.29 on 2026-03-10 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        (
            "authentication",
            "0003_alter_organization_logo_alter_organization_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Consultant name", max_length=200)),
                (
                    "consultant_type",
                    models.CharField(
                        choices=[
                            ("ARCHITECT", "Architect"),
                            ("STRUCTURAL_ENGINEER", "Structural Engineer"),
                            ("MECHANICAL_ENGINEER", "Mechanical Engineer"),
                            ("ELECTRICAL_ENGINEER", "Electrical Engineer"),
                            ("QUANTITY_SURVEYOR", "Quantity Surveyor"),
                            ("SERVICES_ENGINEER", "Services Engineer"),
                            ("PLUMBING_ENGINEER", "Plumbing Engineer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Company/Firm name", max_length=200
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultants",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultant",
                "verbose_name_plural": "Consultants",
                "db_table": "consultants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("DESIGN", "Design Fees"),
                            ("SUPERVISION", "Supervision Fees"),
                            ("INSPECTION", "Inspection Fees"),
                            ("CERTIFICATION", "Certification Fees"),
                            ("CONSULTANCY", "General Consultancy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total agreed fee amount",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_schedule",
                    models.TextField(
                        blank=True, help_text="Payment terms and schedule"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees",
                        to="consultants.consultant",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_fees",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultant Fee",
                "verbose_name_plural": "Consultant Fees",
                "db_table": "consultant_fees",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectConsultant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role on this project (e.g., 'Lead Architect', 'Supervision Engineer')",
                        max_length=100,
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_assignments",
                        to="consultants.consultant",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_consultants",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Consultant",
                "verbose_name_plural": "Project Consultants",
                "db_table": "project_consultants",
                "indexes": [
                    models.Index(
                        fields=["project", "is_active"],
                        name="project_con_project_33f738_idx",
                    )
                ],
                "unique_together": {("project", "consultant")},
            },
        ),
        migrations.CreateModel(
            name="ConsultantPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_date", models.DateField()),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Bank Transfer, Cheque, Cash",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant_fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="consultants.consultantfee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultant Payment",
                "verbose_name_plural": "Consultant Payments",
                "db_table": "consultant_payments",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["consultant_fee", "payment_date"],
                        name="consultant__consult_dcbb3a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="consultantfee",
            index=models.Index(
                fields=["consultant", "project"], name="consultant__consult_010dee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantfee",
            index=models.Index(
                fields=["project"], name="consultant__project_711870_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultant",
            index=models.Index(
                fields=["organization", "consultant_type"],
                name="consultants_organiz_06fd5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultant",
            index=models.Index(fields=["name"], name="consultants_name_5ab45a_idx"),
        ),
    ]
