# Generated by Django 4.2.29 on 2026-03-11 18:01

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "authentication",
            "0003_projectaccess_project_projectaccess_user_user_groups_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Report name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Report description"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PROJECT_FINANCIAL", "Project Financial Summary"),
                            ("CASH_FLOW", "Cash Flow Forecast Report"),
                            ("VARIATION_IMPACT", "Variation Impact Report"),
                            ("SUBCONTRACTOR_PAYMENT", "Subcontractor Payment Report"),
                            ("DOCUMENT_AUDIT", "Document Audit Report"),
                            ("PROCUREMENT_SUMMARY", "Procurement Summary"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        help_text="Type of report",
                        max_length=50,
                    ),
                ),
                (
                    "default_parameters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Default report parameters"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether report is active"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether report is visible to all users in organization",
                    ),
                ),
                (
                    "cache_duration",
                    models.IntegerField(
                        default=300,
                        help_text="Cache duration in seconds (0 = no cache)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When report was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When report was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reporting_report",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Schedule name", max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("CUSTOM", "Custom (Cron)"),
                        ],
                        default="DAILY",
                        help_text="Report frequency",
                        max_length=20,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for CUSTOM frequency",
                        max_length=100,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("EXCEL", "Excel Spreadsheet"),
                            ("CSV", "CSV File"),
                            ("JSON", "JSON Data"),
                        ],
                        default="PDF",
                        help_text="Export format for scheduled report",
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Report parameters for this schedule",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("DASHBOARD", "Dashboard"),
                            ("STORAGE", "File Storage"),
                            ("ALL", "All Methods"),
                        ],
                        default="EMAIL",
                        help_text="How to deliver the report",
                        max_length=20,
                    ),
                ),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        help_text="Email recipients (for EMAIL delivery)",
                        size=None,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether schedule is active"
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, help_text="Last execution time", null=True
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, help_text="Next scheduled execution time", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When schedule was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When schedule was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this schedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Report to schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reporting.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Schedule",
                "verbose_name_plural": "Report Schedules",
                "db_table": "reporting_schedule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CACHED", "Cached"),
                        ],
                        default="PENDING",
                        help_text="Execution status",
                        max_length=20,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("EXCEL", "Excel Spreadsheet"),
                            ("CSV", "CSV File"),
                            ("JSON", "JSON Data"),
                        ],
                        help_text="Export format used",
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters used for this execution"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to generated report file",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "row_count",
                    models.IntegerField(
                        blank=True, help_text="Number of data rows in report", null=True
                    ),
                ),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True, help_text="Execution time in seconds", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "stack_trace",
                    models.TextField(blank=True, help_text="Stack trace if failed"),
                ),
                (
                    "cache_key",
                    models.CharField(
                        blank=True,
                        help_text="Redis cache key for cached results",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When execution was initiated"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution completed", null=True
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        help_text="User who executed this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Report that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reporting.report",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Schedule that triggered this execution (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="reporting.reportschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Execution",
                "verbose_name_plural": "Report Executions",
                "db_table": "reporting_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Widget name", max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("KPI", "Key Performance Indicator"),
                            ("CHART", "Chart"),
                            ("TABLE", "Data Table"),
                            ("GAUGE", "Gauge"),
                            ("TREND", "Trend Line"),
                        ],
                        default="KPI",
                        help_text="Widget visualization type",
                        max_length=20,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LINE", "Line Chart"),
                            ("BAR", "Bar Chart"),
                            ("PIE", "Pie Chart"),
                            ("DONUT", "Donut Chart"),
                            ("AREA", "Area Chart"),
                        ],
                        help_text="Chart type (for CHART widgets)",
                        max_length=20,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        help_text="Data source identifier (e.g., 'project_count', 'total_revenue')",
                        max_length=100,
                    ),
                ),
                (
                    "query_parameters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Parameters for data query"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Display order on dashboard"
                    ),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=300,
                        help_text="Auto-refresh interval in seconds (0 = no refresh)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class (e.g., 'fa-dollar-sign')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Widget color (hex or color name)",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether widget is active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When widget was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When widget was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this widget",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this widget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_widgets",
                        to="authentication.organization",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated report (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="reporting.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "db_table": "reporting_widget",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="reporting_w_organiz_1670fd_idx",
                    ),
                    models.Index(
                        fields=["display_order"], name="reporting_w_display_fc83fa_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["report", "is_active"], name="reporting_s_report__2725e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["next_run"], name="reporting_s_next_ru_a52934_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["report", "status"], name="reporting_e_report__fdb663_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["created_at"], name="reporting_e_created_0d3943_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["cache_key"], name="reporting_e_cache_k_028b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["organization", "is_active"],
                name="reporting_r_organiz_8353ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type"], name="reporting_r_report__5d34ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_at"], name="reporting_r_created_1523d4_idx"
            ),
        ),
    ]
