# Generated by Django 4.2.29 on 2026-03-17 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_report_builder_and_sequence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="report",
            new_name="reporting_r_module_41feef_idx",
            old_name="reporting_r_module_9c5d49_idx",
        ),
        migrations.AlterField(
            model_name="report",
            name="sequence",
            field=models.IntegerField(
                default=0,
                help_text="Sequence number within organization year",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
