# Generated by Django 4.2.29 on 2026-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporting",
            "0003_rename_reporting_r_module_9c5d49_idx_reporting_r_module_41feef_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reportexecution",
            name="attempt_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of execution attempts"
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="cache_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When cached result expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum retry attempts"
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Execution progress percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="queued_at",
            field=models.DateTimeField(
                blank=True, help_text="When execution was queued", null=True
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="When execution started", null=True
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="worker_id",
            field=models.CharField(
                blank=True,
                help_text="Worker identity that processed execution",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="reportexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CACHED", "Cached"),
                ],
                default="PENDING",
                help_text="Execution status",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["status", "progress"], name="reporting_e_status_bb7d8e_idx"
            ),
        ),
    ]
