# Generated by Django 4.2.29 on 2026-03-11 07:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("suppliers", "0002_alter_localpurchaseorder_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the issue", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the issue"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("reported_date", models.DateTimeField(auto_now_add=True)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes on how the issue was resolved",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_issues_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_issues",
                        to="projects.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_issues_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Issue",
                "verbose_name_plural": "Site Issues",
                "db_table": "site_issues",
                "ordering": ["-severity", "-reported_date"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="site_issues_project_868075_idx",
                    ),
                    models.Index(
                        fields=["project", "-reported_date"],
                        name="site_issues_project_46787b_idx",
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="site_issues_severit_ebed66_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="site_issues_assigne_11cc10_idx",
                    ),
                    models.Index(
                        fields=["status"], name="site_issues_status_2d109f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Supplier name if not in system",
                        max_length=255,
                    ),
                ),
                ("material_name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="units",
                        help_text="Unit of measurement (e.g., bags, tons, m³, pieces)",
                        max_length=50,
                    ),
                ),
                ("delivery_note_number", models.CharField(max_length=100)),
                ("delivery_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Inspection"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("PARTIAL", "Partially Accepted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes or observations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_deliveries",
                        to="projects.project",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier who delivered the material",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_deliveries",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Delivery",
                "verbose_name_plural": "Material Deliveries",
                "db_table": "material_deliveries",
                "ordering": ["-delivery_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-delivery_date"],
                        name="material_de_project_f72b2e_idx",
                    ),
                    models.Index(
                        fields=["supplier", "-delivery_date"],
                        name="material_de_supplie_e7a6b0_idx",
                    ),
                    models.Index(
                        fields=["delivery_date"], name="material_de_deliver_fe6f37_idx"
                    ),
                    models.Index(
                        fields=["status"], name="material_de_status_2de092_idx"
                    ),
                    models.Index(
                        fields=["delivery_note_number"],
                        name="material_de_deliver_c0c424_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailySiteReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "weather",
                    models.CharField(
                        choices=[
                            ("SUNNY", "Sunny"),
                            ("CLOUDY", "Cloudy"),
                            ("RAINY", "Rainy"),
                            ("STORMY", "Stormy"),
                        ],
                        default="SUNNY",
                        max_length=20,
                    ),
                ),
                (
                    "labour_summary",
                    models.TextField(
                        help_text="Summary of labour on site (e.g., '20 masons, 15 labourers, 5 carpenters')"
                    ),
                ),
                (
                    "work_completed",
                    models.TextField(
                        help_text="Description of work completed during the day"
                    ),
                ),
                (
                    "materials_delivered",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Materials delivered to site today (if any)",
                    ),
                ),
                (
                    "issues",
                    models.TextField(
                        blank=True, default="", help_text="Any issues or concerns noted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_reports_prepared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_reports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Site Report",
                "verbose_name_plural": "Daily Site Reports",
                "db_table": "daily_site_reports",
                "ordering": ["-report_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-report_date"],
                        name="daily_site__project_c51f7c_idx",
                    ),
                    models.Index(
                        fields=["report_date"], name="daily_site__report__990836_idx"
                    ),
                    models.Index(
                        fields=["prepared_by"], name="daily_site__prepare_61d823_idx"
                    ),
                ],
                "unique_together": {("project", "report_date")},
            },
        ),
    ]
