# Generated by Django 4.2.29 on 2026-03-11 15:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "authentication",
            "0003_projectaccess_project_projectaccess_user_user_groups_and_more",
        ),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcontractAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_reference",
                    models.CharField(
                        help_text="Unique contract reference number (e.g., SC-2026-001)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "scope_of_work",
                    models.TextField(
                        help_text="Detailed description of work to be performed"
                    ),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total contract value (excluding VAT)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "retention_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Retention percentage to withhold from payments",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("start_date", models.DateField(help_text="Contract start date")),
                ("end_date", models.DateField(help_text="Contract end date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft - Under Preparation"),
                            ("ACTIVE", "Active - Work in Progress"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current status of the subcontract",
                        max_length=20,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="Payment terms (e.g., Net 30 days)",
                        max_length=255,
                    ),
                ),
                (
                    "vat_applicable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether VAT is applicable to this contract",
                    ),
                ),
                (
                    "performance_bond_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a performance bond is required",
                    ),
                ),
                (
                    "performance_bond_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Performance bond percentage if required",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional contract notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when contract was activated",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when contract was completed",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this subcontract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subcontracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this subcontract belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontracts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontract Agreement",
                "verbose_name_plural": "Subcontract Agreements",
                "db_table": "subcontract_agreements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subcontractor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subcontractor company name", max_length=255
                    ),
                ),
                (
                    "company_registration",
                    models.CharField(
                        blank=True,
                        help_text="Company registration number",
                        max_length=100,
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        help_text="Tax identification number / VAT number",
                        max_length=100,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Primary contact person name", max_length=255
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address", max_length=254
                    ),
                ),
                ("address", models.TextField(help_text="Physical address")),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Area of specialization (e.g., Electrical, Plumbing, Masonry)",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this subcontractor is active for new contracts",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the subcontractor"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when subcontractor was created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this subcontractor record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subcontractors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that manages this subcontractor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractors",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontractor",
                "verbose_name_plural": "Subcontractors",
                "db_table": "subcontractors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "claim_number",
                    models.CharField(
                        help_text="Sequential claim number (e.g., SC-001-C001)",
                        max_length=50,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start date of claim period"),
                ),
                ("period_end", models.DateField(help_text="End date of claim period")),
                (
                    "claimed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount claimed by subcontractor",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "certified_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount certified by project team",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "retention_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Retention amount withheld from payment",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "previous_cumulative_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cumulative certified amount from previous claims",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft - Being Prepared"),
                            ("SUBMITTED", "Submitted - Awaiting Certification"),
                            ("CERTIFIED", "Certified - Approved for Payment"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current status of the claim",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time claim was submitted",
                        null=True,
                    ),
                ),
                (
                    "certified_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time claim was certified",
                        null=True,
                    ),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time payment was made",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of work performed in this period",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if claim was rejected",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this claim"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who certified the claim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_subcontract_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this claim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subcontract_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcontract",
                    models.ForeignKey(
                        help_text="Subcontract agreement this claim belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="subcontracts.subcontractagreement",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted the claim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_subcontract_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontract Claim",
                "verbose_name_plural": "Subcontract Claims",
                "db_table": "subcontract_claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subcontractagreement",
            name="subcontractor",
            field=models.ForeignKey(
                help_text="Subcontractor performing the work",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcontracts",
                to="subcontracts.subcontractor",
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractor",
            index=models.Index(
                fields=["organization", "is_active"],
                name="subcontract_organiz_f01245_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractor",
            index=models.Index(fields=["name"], name="subcontract_name_b6cb64_idx"),
        ),
        migrations.AddConstraint(
            model_name="subcontractor",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_subcontractor_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractclaim",
            index=models.Index(
                fields=["subcontract", "status"], name="subcontract_subcont_1c973d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractclaim",
            index=models.Index(fields=["status"], name="subcontract_status_d9a5c3_idx"),
        ),
        migrations.AddIndex(
            model_name="subcontractclaim",
            index=models.Index(
                fields=["submitted_date"], name="subcontract_submitt_94402a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractclaim",
            index=models.Index(
                fields=["certified_date"], name="subcontract_certifi_d221c3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcontractclaim",
            constraint=models.UniqueConstraint(
                fields=("subcontract", "claim_number"),
                name="unique_claim_number_per_subcontract",
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractagreement",
            index=models.Index(
                fields=["project", "status"], name="subcontract_project_bd28a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractagreement",
            index=models.Index(
                fields=["subcontractor"], name="subcontract_subcont_55820f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractagreement",
            index=models.Index(fields=["status"], name="subcontract_status_0f8d6c_idx"),
        ),
        migrations.AddIndex(
            model_name="subcontractagreement",
            index=models.Index(
                fields=["start_date", "end_date"], name="subcontract_start_d_582d44_idx"
            ),
        ),
    ]
