# Generated by Django 4.2.29 on 2026-03-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subcontracts", "0002_contract_claim_sequences"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subcontractagreement",
            new_name="subcontract_organiz_39dc68_idx",
            old_name="subcontrac_organiz_41a7e1_idx",
        ),
        migrations.RenameIndex(
            model_name="subcontractclaim",
            new_name="subcontract_project_4bf746_idx",
            old_name="subcontrac_project_7b4f99_idx",
        ),
    ]
