# Generated by Django 4.2.29 on 2026-03-11 12:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioCashFlowSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_month",
                    models.DateField(
                        help_text="First day of the forecast month (YYYY-MM-01)",
                        unique=True,
                    ),
                ),
                (
                    "total_portfolio_inflow",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_portfolio_outflow",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "net_portfolio_cash_flow",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cumulative_portfolio_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cumulative portfolio cash balance",
                        max_digits=15,
                    ),
                ),
                ("active_projects_count", models.IntegerField(default=0)),
                ("projects_with_negative_flow", models.IntegerField(default=0)),
                ("forecast_generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portfolio Cash Flow Summary",
                "verbose_name_plural": "Portfolio Cash Flow Summaries",
                "db_table": "portfolio_cashflow_summary",
                "ordering": ["forecast_month"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_month",
                    models.DateField(
                        help_text="First day of the forecast month (YYYY-MM-01)"
                    ),
                ),
                (
                    "forecast_generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this forecast was computed"
                    ),
                ),
                (
                    "expected_valuations",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected IPC/valuation submissions",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_client_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected client payments (approved valuations)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_retention_releases",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected retention money releases",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_variation_order_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected variation order payments",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_inflow",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all expected inflows",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_supplier_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected supplier invoice payments",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_labour_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected labour/payroll costs",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_consultant_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected consultant/professional fees",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_procurement_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected procurement-related payments",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_site_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected site operational expenses",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_other_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Other expected expenses",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_outflow",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all expected outflows",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "net_cash_flow",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Net cash flow (inflow - outflow)",
                        max_digits=15,
                    ),
                ),
                (
                    "cumulative_cash_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cumulative project cash balance up to this month",
                        max_digits=15,
                    ),
                ),
                (
                    "is_actual",
                    models.BooleanField(
                        default=False,
                        help_text="True if this month has actual data (not forecast)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flow_forecasts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Flow Forecast",
                "verbose_name_plural": "Cash Flow Forecasts",
                "db_table": "cashflow_forecast",
                "ordering": ["project", "forecast_month"],
                "indexes": [
                    models.Index(
                        fields=["project", "forecast_month"],
                        name="cashflow_fo_project_ca0b39_idx",
                    ),
                    models.Index(
                        fields=["forecast_month"], name="cashflow_fo_forecas_26c6a0_idx"
                    ),
                    models.Index(
                        fields=["is_actual"], name="cashflow_fo_is_actu_872afc_idx"
                    ),
                ],
                "unique_together": {("project", "forecast_month")},
            },
        ),
    ]
