# Generated by Django 4.2.29 on 2026-03-11 13:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowforecast",
            name="confidence_level",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Confidence"),
                    ("MEDIUM", "Medium Confidence"),
                    ("HIGH", "High Confidence"),
                ],
                default="MEDIUM",
                help_text="Forecast reliability based on project progress, historical data, and variance",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="portfoliocashflowsummary",
            name="average_cash_burn_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Average monthly cash outflow across portfolio (burn rate)",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="portfoliocashflowsummary",
            name="cash_runway_months",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                help_text="Estimated months of operation with current cash balance (balance / burn_rate)",
                max_digits=5,
            ),
        ),
    ]
