# Generated by Django 4.2.29 on 2026-03-11 07:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("bq", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Valuation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "valuation_number",
                    models.CharField(
                        help_text="Unique valuation number (e.g., IPC-001)",
                        max_length=50,
                    ),
                ),
                ("valuation_date", models.DateField(help_text="Date of valuation")),
                (
                    "work_completed_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value of work completed to date",
                        max_digits=15,
                    ),
                ),
                (
                    "retention_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Retention percentage (typically 5-10%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "retention_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Retention amount held back",
                        max_digits=15,
                    ),
                ),
                (
                    "previous_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total of all previous payments",
                        max_digits=15,
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount due this valuation",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or comments"
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="Date and time of approval", null=True
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, help_text="Date payment was made", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuations_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuations",
                        to="projects.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuations_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Valuation",
                "verbose_name_plural": "Valuations",
                "db_table": "valuations",
                "ordering": ["-valuation_date", "-valuation_number"],
            },
        ),
        migrations.CreateModel(
            name="BQItemProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity completed in previous valuations",
                        max_digits=12,
                    ),
                ),
                (
                    "this_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity completed this period",
                        max_digits=12,
                    ),
                ),
                (
                    "cumulative_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total quantity completed to date",
                        max_digits=12,
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Value from previous valuations",
                        max_digits=15,
                    ),
                ),
                (
                    "this_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Value of work this period",
                        max_digits=15,
                    ),
                ),
                (
                    "cumulative_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value to date",
                        max_digits=15,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this item's progress"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bq_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="bq.bqitem",
                    ),
                ),
                (
                    "valuation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_progress",
                        to="valuations.valuation",
                    ),
                ),
            ],
            options={
                "verbose_name": "BQ Item Progress",
                "verbose_name_plural": "BQ Item Progress",
                "db_table": "bq_item_progress",
                "ordering": ["valuation", "bq_item"],
            },
        ),
        migrations.AddIndex(
            model_name="valuation",
            index=models.Index(
                fields=["project", "-valuation_date"],
                name="valuations_project_76947e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="valuation",
            index=models.Index(fields=["status"], name="valuations_status_7e00bb_idx"),
        ),
        migrations.AddIndex(
            model_name="valuation",
            index=models.Index(
                fields=["valuation_number"], name="valuations_valuati_c3b45e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="valuation",
            unique_together={("project", "valuation_number")},
        ),
        migrations.AddIndex(
            model_name="bqitemprogress",
            index=models.Index(
                fields=["valuation"], name="bq_item_pro_valuati_285173_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bqitemprogress",
            index=models.Index(
                fields=["bq_item"], name="bq_item_pro_bq_item_611d83_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bqitemprogress",
            unique_together={("valuation", "bq_item")},
        ),
    ]
