# Generated by Django 4.2.29 on 2026-03-10 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Document name", max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DRAWINGS", "Architectural Drawings"),
                            ("STRUCTURAL_DRAWINGS", "Structural Drawings"),
                            ("MECHANICAL_DRAWINGS", "Mechanical Drawings"),
                            ("ELECTRICAL_DRAWINGS", "Electrical Drawings"),
                            ("APPROVALS", "Approval Documents"),
                            ("INVOICES", "Invoices"),
                            ("RECEIPTS", "Receipts"),
                            ("BQ", "Bill of Quantities"),
                            ("CONTRACT", "Contract Documents"),
                            ("REPORTS", "Progress Reports"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="Version number (e.g., v1.0, Rev A)", max_length=20
                    ),
                ),
                (
                    "file_path",
                    models.CharField(help_text="Path to document file", max_length=500),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=True, help_text="Is this the current version?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Version notes/changelog"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Version",
                "verbose_name_plural": "Document Versions",
                "db_table": "document_versions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "is_latest"],
                        name="document_ve_documen_ba068b_idx",
                    )
                ],
                "unique_together": {("document", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["project", "document_type"], name="documents_project_717bb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="documents_documen_fc21d0_idx"
            ),
        ),
    ]
