# Generated by Django 4.2.29 on 2026-03-11 14:38

import apps.documents.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "authentication",
            "0003_projectaccess_project_projectaccess_user_user_groups_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Contract Document"),
                            ("LPO_ATTACHMENT", "LPO Attachment"),
                            ("DELIVERY_NOTE", "Delivery Note"),
                            ("SUPPLIER_INVOICE", "Supplier Invoice"),
                            ("PAYMENT_VOUCHER", "Payment Voucher"),
                            ("DRAWING", "Technical Drawing"),
                            ("BOQ", "Bill of Quantities"),
                            ("SPECIFICATION", "Technical Specification"),
                            ("METHOD_STATEMENT", "Method Statement"),
                            ("SITE_PHOTO", "Site Photo"),
                            ("SITE_REPORT_ATTACHMENT", "Site Report Attachment"),
                            ("PROGRESS_REPORT", "Progress Report"),
                            ("VARIATION_INSTRUCTION", "Variation Instruction"),
                            ("VALUATION_CERTIFICATE", "Valuation Certificate"),
                            ("RISK_ASSESSMENT", "Risk Assessment"),
                            ("PERMIT", "Permit/License"),
                            ("QUALITY_DOCUMENT", "Quality Document"),
                            ("SAFETY_DOCUMENT", "Safety Document"),
                            ("CORRESPONDENCE", "Correspondence/Letter"),
                            ("MEETING_MINUTES", "Meeting Minutes"),
                            ("OTHER", "Other Document"),
                        ],
                        db_index=True,
                        help_text="Classification of document",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Document description and notes"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Document file",
                        upload_to=apps.documents.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "bmp",
                                    "webp",
                                    "svg",
                                    "dwg",
                                    "dxf",
                                    "rvt",
                                    "zip",
                                    "rar",
                                    "7z",
                                    "txt",
                                    "csv",
                                    "xml",
                                    "json",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="File size in bytes (auto-populated)",
                        null=True,
                    ),
                ),
                (
                    "file_extension",
                    models.CharField(
                        blank=True,
                        help_text="File extension (auto-populated)",
                        max_length=10,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Document version number"
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this is the latest version",
                    ),
                ),
                (
                    "version_notes",
                    models.TextField(
                        blank=True, help_text="Notes about this version (changes made)"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for searching",
                        max_length=255,
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Mark as confidential (restricted access)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Document expiry date (for permits, licenses)",
                        null=True,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number",
                        max_length=100,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of related object (e.g., LPO, Variation)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization owning this document",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="authentication.organization",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to previous version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="documents.document",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this document belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "document_type"],
                        name="documents_project_717bb5_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="documents_content_7d700d_idx",
                    ),
                    models.Index(
                        fields=["is_latest", "document_type"],
                        name="documents_is_late_648f48_idx",
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="documents_uploade_d6a956_idx"
                    ),
                    models.Index(
                        fields=["is_confidential"], name="documents_is_conf_4ece8e_idx"
                    ),
                ],
            },
        ),
    ]
