# Generated by Django 4.2.29 on 2026-03-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="signature_hash",
            field=models.CharField(
                blank=True,
                help_text="Cryptographic hash of signature for verification",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="signed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date and time when document was signed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who digitally signed this document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public - All Users"),
                    ("PROJECT_TEAM", "Project Team Only"),
                    ("FINANCE_ONLY", "Finance Team Only"),
                    ("ADMIN_ONLY", "Admin Only"),
                    ("CONFIDENTIAL", "Confidential - Restricted Access"),
                ],
                db_index=True,
                default="PROJECT_TEAM",
                help_text="Controls who can view this document",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["signed_at"], name="documents_signed__1a6548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["visibility"], name="documents_visibil_8cb5d7_idx"
            ),
        ),
    ]
