# Generated by Django 4.2.29 on 2026-03-10 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        choices=[
                            ("COUNTY", "County Government"),
                            ("NCA", "National Construction Authority"),
                            ("NEMA", "National Environment Management Authority"),
                            ("FIRE_DEPT", "Fire Department"),
                            ("PUBLIC_HEALTH", "Public Health Department"),
                            ("OTHER", "Other Authority"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("PLANNING_PERMIT", "Planning Permit"),
                            ("BUILDING_PERMIT", "Building Permit"),
                            ("OCCUPANCY_CERTIFICATE", "Occupancy Certificate"),
                            ("NCA_REGISTRATION", "NCA Project Registration"),
                            ("ENVIRONMENTAL_IMPACT", "Environmental Impact Assessment"),
                            ("FIRE_CERTIFICATE", "Fire Safety Certificate"),
                            ("HEALTH_CERTIFICATE", "Public Health Certificate"),
                            ("OTHER", "Other Approval"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("application_date", models.DateField(blank=True, null=True)),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, help_text="Date approval was granted", null=True
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Date approval expires", null=True
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Official approval reference number",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Approval",
                "verbose_name_plural": "Project Approvals",
                "db_table": "project_approvals",
                "ordering": ["-approval_date"],
            },
        ),
    ]
