# Generated by Django 4.2.29 on 2026-03-10 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
        ("projects", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapproval",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="Scanned approval document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvals",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="projectapproval",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="projectapproval",
            index=models.Index(
                fields=["project", "authority"], name="project_app_project_2f049a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectapproval",
            index=models.Index(fields=["status"], name="project_app_status_39b46d_idx"),
        ),
        migrations.AddIndex(
            model_name="projectapproval",
            index=models.Index(
                fields=["approval_type"], name="project_app_approva_8923ee_idx"
            ),
        ),
    ]
