# Generated by Django 4.2.29 on 2026-03-10 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        (
            "authentication",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalPurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lpo_number",
                    models.CharField(
                        help_text="Unique LPO number", max_length=50, unique=True
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total LPO value", max_digits=15
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PARTIALLY_DELIVERED", "Partially Delivered"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=25,
                    ),
                ),
                ("delivery_deadline", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lpos",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Purchase Order",
                "verbose_name_plural": "Local Purchase Orders",
                "db_table": "local_purchase_orders",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Supplier name", max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "tax_pin",
                    models.CharField(
                        blank=True, help_text="Tax PIN/VAT number", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100)),
                ("invoice_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Payment"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Fully Paid"),
                            ("DISPUTED", "Disputed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lpo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked LPO if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="suppliers.localpurchaseorder",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_invoices",
                        to="projects.project",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Invoice",
                "verbose_name_plural": "Supplier Invoices",
                "db_table": "supplier_invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="LPOItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Material/Item description", max_length=200
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity ordered", max_digits=10
                    ),
                ),
                (
                    "unit",
                    models.CharField(help_text="Unit of measurement", max_length=50),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "delivered_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity delivered so far",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "lpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="suppliers.localpurchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "LPO Item",
                "verbose_name_plural": "LPO Items",
                "db_table": "lpo_items",
                "ordering": ["lpo", "id"],
            },
        ),
        migrations.AddField(
            model_name="localpurchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lpos",
                to="suppliers.supplier",
            ),
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="suppliers.supplierinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Payment",
                "verbose_name_plural": "Supplier Payments",
                "db_table": "supplier_payments",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["supplier_invoice", "payment_date"],
                        name="supplier_pa_supplie_067e4c_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(
                fields=["supplier", "project"], name="supplier_in_supplie_0a1198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(fields=["status"], name="supplier_in_status_886f23_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(
                fields=["invoice_date"], name="supplier_in_invoice_30d23d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplierinvoice",
            unique_together={("supplier", "invoice_number")},
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["organization", "is_active"],
                name="suppliers_organiz_7c1388_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["name"], name="suppliers_name_ed482a_idx"),
        ),
        migrations.AddIndex(
            model_name="lpoitem",
            index=models.Index(fields=["lpo"], name="lpo_items_lpo_id_125a15_idx"),
        ),
        migrations.AddIndex(
            model_name="localpurchaseorder",
            index=models.Index(
                fields=["lpo_number"], name="local_purch_lpo_num_054e0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="localpurchaseorder",
            index=models.Index(
                fields=["supplier", "project"], name="local_purch_supplie_9f6585_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="localpurchaseorder",
            index=models.Index(fields=["status"], name="local_purch_status_8eacfb_idx"),
        ),
    ]
