# Generated by Django 4.2.29 on 2026-03-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("ISSUED", "Issued"),
                    ("PARTIALLY_DELIVERED", "Partially Delivered"),
                    ("DELIVERED", "Delivered"),
                    ("INVOICED", "Invoiced"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=25,
            ),
        ),
    ]
