# Generated by Django 4.2.29 on 2026-03-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_lpo_sequence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="localpurchaseorder",
            new_name="local_purch_project_cfdba1_idx",
            old_name="local_purch_project_f33786_idx",
        ),
    ]
