# Generated by Django 4.2.29 on 2026-03-10 23:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BQElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Element name (e.g., Foundation)", max_length=200
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within section"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "BQ Element",
                "verbose_name_plural": "BQ Elements",
                "db_table": "bq_elements",
                "ordering": ["section", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BQSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section name (e.g., Substructure)", max_length=200
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bq_sections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "BQ Section",
                "verbose_name_plural": "BQ Sections",
                "db_table": "bq_sections",
                "ordering": ["project", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BQItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed item description"),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (e.g., m², m³, m, No.)",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity per unit", max_digits=12
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate per unit", max_digits=12
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount (quantity × rate)",
                        max_digits=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bq.bqelement",
                    ),
                ),
            ],
            options={
                "verbose_name": "BQ Item",
                "verbose_name_plural": "BQ Items",
                "db_table": "bq_items",
                "ordering": ["element", "id"],
            },
        ),
        migrations.AddField(
            model_name="bqelement",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="bq.bqsection",
            ),
        ),
        migrations.AddIndex(
            model_name="bqsection",
            index=models.Index(
                fields=["project", "order"], name="bq_sections_project_6c6825_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bqsection",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="bqitem",
            index=models.Index(fields=["element"], name="bq_items_element_533a1f_idx"),
        ),
        migrations.AddIndex(
            model_name="bqelement",
            index=models.Index(
                fields=["section", "order"], name="bq_elements_section_d69f5d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bqelement",
            unique_together={("section", "name")},
        ),
    ]
