# Generated by Django 4.2.29 on 2026-03-10 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_project_uuid_conversion"),
        (
            "authentication",
            "0003_alter_organization_logo_alter_organization_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Worker name", max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID or identification number",
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MASON", "Mason"),
                            ("CARPENTER", "Carpenter"),
                            ("ELECTRICIAN", "Electrician"),
                            ("PLUMBER", "Plumber"),
                            ("PAINTER", "Painter"),
                            ("WELDER", "Welder"),
                            ("LABOURER", "General Labourer"),
                            ("STEEL_FIXER", "Steel Fixer"),
                            ("TILE_SETTER", "Tile Setter"),
                            ("FOREMAN", "Foreman"),
                            ("OTHER", "Other"),
                        ],
                        default="LABOURER",
                        max_length=20,
                    ),
                ),
                (
                    "default_daily_wage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard daily wage for this worker",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "db_table": "workers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyLabourRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Work date")),
                (
                    "daily_wage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid for this day",
                        max_digits=8,
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=1,
                        default=8.0,
                        help_text="Hours worked",
                        max_digits=4,
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False, help_text="Whether payment has been made"
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Work notes or comments"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_labour_records",
                        to="projects.project",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_records",
                        to="workers.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Labour Record",
                "verbose_name_plural": "Daily Labour Records",
                "db_table": "daily_labour_records",
                "ordering": ["-date", "project"],
            },
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(
                fields=["organization", "role"], name="workers_organiz_9baf8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(fields=["name"], name="workers_name_d1fe14_idx"),
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(fields=["is_active"], name="workers_is_acti_e9f21c_idx"),
        ),
        migrations.AddIndex(
            model_name="dailylabourrecord",
            index=models.Index(
                fields=["project", "date"], name="daily_labou_project_0564a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailylabourrecord",
            index=models.Index(
                fields=["worker", "date"], name="daily_labou_worker__115cf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailylabourrecord",
            index=models.Index(fields=["paid"], name="daily_labou_paid_842b49_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailylabourrecord",
            unique_together={("project", "worker", "date")},
        ),
    ]
