# Generated by Django 4.2.29 on 2026-03-11 13:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique variation order reference (e.g., VO-2026-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the variation", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the variation and justification"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("SCOPE_CHANGE", "Scope Change"),
                            ("DESIGN_CHANGE", "Design Change"),
                            ("SITE_CONDITION", "Site Condition"),
                            ("CLIENT_REQUEST", "Client Request"),
                            ("REGULATORY", "Regulatory/Compliance"),
                            ("OTHER", "Other"),
                        ],
                        default="SCOPE_CHANGE",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Priority"),
                            ("MEDIUM", "Medium Priority"),
                            ("HIGH", "High Priority"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "instruction_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of instruction/request",
                    ),
                ),
                (
                    "required_by_date",
                    models.DateField(
                        blank=True,
                        help_text="Date by which variation must be completed",
                        null=True,
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date variation was submitted for approval",
                        null=True,
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="Date variation was approved", null=True
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated cost of variation (initial quote)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "approved_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final approved value (may differ from estimate)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "invoiced_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount invoiced for this variation",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "paid_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount paid for this variation",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("INVOICED", "Invoiced"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text="Business justification for the variation"
                    ),
                ),
                (
                    "client_reference",
                    models.CharField(
                        blank=True,
                        help_text="Client's reference number for this variation",
                        max_length=100,
                    ),
                ),
                (
                    "impact_on_schedule",
                    models.TextField(
                        blank=True, help_text="Impact on project timeline"
                    ),
                ),
                (
                    "technical_notes",
                    models.TextField(
                        blank=True, help_text="Technical specifications and notes"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection (if status is REJECTED)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this variation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variations_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this variation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variation_orders",
                        to="projects.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted for approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variations_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Variation Order",
                "verbose_name_plural": "Variation Orders",
                "db_table": "variation_orders",
                "ordering": ["-instruction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="variation_o_project_3988ec_idx",
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="variation_o_referen_177f51_idx",
                    ),
                    models.Index(
                        fields=["status"], name="variation_o_status_99c88e_idx"
                    ),
                    models.Index(
                        fields=["instruction_date"],
                        name="variation_o_instruc_b2ddff_idx",
                    ),
                ],
            },
        ),
    ]
