# Generated by Django 4.2.29 on 2026-03-11 14:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("variations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variationorder",
            name="certified_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount certified by consultant (may differ from approved value)",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="variationorder",
            name="certified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Consultant who certified this variation (QS, Architect, Engineer)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variations_certified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="variationorder",
            name="certified_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date variation was certified by consultant",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="variationorder",
            name="variation_type",
            field=models.CharField(
                choices=[
                    ("CLIENT_INSTRUCTION", "Client Instruction"),
                    ("DESIGN_CHANGE", "Design Change"),
                    ("ADDITIONAL_WORK", "Additional Work"),
                    ("OMISSION", "Omission/Deduction"),
                    ("ERROR_CORRECTION", "Error Correction"),
                    ("UNFORESEEN_CONDITION", "Unforeseen Site Condition"),
                ],
                default="ADDITIONAL_WORK",
                help_text="Classification of variation for cost analysis",
                max_length=25,
            ),
        ),
    ]
