# Generated by Django 4.2.29 on 2026-03-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variations", "0003_variationorder_sequence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="variationorder",
            new_name="variation_o_project_88ea24_idx",
            old_name="variationor_project_4d75e7_idx",
        ),
    ]
