# Generated by Django 4.2.29 on 2026-03-10 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("bq", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("MATERIALS", "Materials"),
                            ("LABOUR", "Labour"),
                            ("CASUAL_LABOUR", "Casual Labour"),
                            ("CONSULTANT", "Consultant Fees"),
                            ("EQUIPMENT", "Equipment Hire"),
                            ("TRANSPORT", "Transport"),
                            ("UTILITIES", "Utilities (Water, Power)"),
                            ("STATUTORY", "Statutory Fees (NCA, County)"),
                            ("INSURANCE", "Insurance"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Expense amount", max_digits=15
                    ),
                ),
                ("date", models.DateField(help_text="Expense date")),
                ("description", models.TextField(help_text="Expense description")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, help_text="Receipt/Invoice number", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "db_table": "expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount allocated to this BQ item",
                        max_digits=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bq_item",
                    models.ForeignKey(
                        help_text="BQ item this expense is allocated to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_allocations",
                        to="bq.bqitem",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="ledger.expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Allocation",
                "verbose_name_plural": "Expense Allocations",
                "db_table": "expense_allocations",
                "ordering": ["expense", "bq_item"],
                "indexes": [
                    models.Index(
                        fields=["expense"], name="expense_all_expense_88a4ca_idx"
                    ),
                    models.Index(
                        fields=["bq_item"], name="expense_all_bq_item_92270c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["project", "expense_type"], name="expenses_project_2996e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["date"], name="expenses_date_a77b87_idx"),
        ),
    ]
