# Generated by Django 4.2.29 on 2026-03-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Approved"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("REQUIRES_APPROVAL", "Requires Approval"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPROVED",
                help_text="Approval status for budget control",
                max_length=25,
            ),
        ),
    ]
