# Generated by Django 4.2.29 on 2026-03-10 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_path",
                    models.CharField(help_text="Path to image file", max_length=500),
                ),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="projects.project",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated construction stage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="projects.projectstage",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Photo",
                "verbose_name_plural": "Project Photos",
                "db_table": "project_photos",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "uploaded_at"],
                        name="project_pho_project_1f7bf7_idx",
                    ),
                    models.Index(
                        fields=["stage"], name="project_pho_stage_i_7bcea8_idx"
                    ),
                ],
            },
        ),
    ]
