# Generated by Django 4.2.29 on 2026-03-10 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectphoto",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated construction stage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="projects.projectstage",
            ),
        ),
        migrations.AddField(
            model_name="projectphoto",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="projectphoto",
            index=models.Index(
                fields=["project", "uploaded_at"], name="project_pho_project_1f7bf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectphoto",
            index=models.Index(fields=["stage"], name="project_pho_stage_i_7bcea8_idx"),
        ),
    ]
