# Generated by Django 4.2.29 on 2026-03-11 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_id", models.UUIDField(db_index=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE_CREATED", "Expense Created"),
                            ("LPO_ISSUED", "LPO Issued"),
                            ("LPO_APPROVED", "LPO Approved"),
                            ("LPO_DELIVERED", "LPO Delivered"),
                            ("SUPPLIER_PAYMENT", "Supplier Payment"),
                            ("CONSULTANT_PAYMENT", "Consultant Payment"),
                            ("CLIENT_PAYMENT", "Client Payment Received"),
                            ("PHOTO_UPLOADED", "Photo Uploaded"),
                            ("STAGE_COMPLETED", "Stage Completed"),
                            ("BUDGET_OVERRUN", "Budget Overrun Detected"),
                            ("APPROVAL_REQUESTED", "Approval Requested"),
                            ("APPROVAL_GRANTED", "Approval Granted"),
                            ("APPROVAL_REJECTED", "Approval Rejected"),
                            ("PROJECT_CREATED", "Project Created"),
                            ("PROJECT_STARTED", "Project Started"),
                            ("PROJECT_COMPLETED", "Project Completed"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (Expense, LPO, etc.)",
                        max_length=50,
                    ),
                ),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount if applicable",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional activity metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Activity",
                "verbose_name_plural": "Project Activities",
                "db_table": "project_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project_id", "-created_at"],
                        name="project_act_project_ed9341_idx",
                    ),
                    models.Index(
                        fields=["activity_type"], name="project_act_activit_3e592f_idx"
                    ),
                    models.Index(
                        fields=["performed_by"], name="project_act_perform_a03b81_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE", "Expense Approval"),
                            ("SUPPLIER_PAYMENT", "Supplier Payment"),
                            ("CONSULTANT_PAYMENT", "Consultant Payment"),
                            ("LPO", "Local Purchase Order"),
                            ("BUDGET_OVERRIDE", "Budget Override"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expense_id", models.UUIDField(blank=True, null=True)),
                ("supplier_payment_id", models.UUIDField(blank=True, null=True)),
                ("consultant_payment_id", models.UUIDField(blank=True, null=True)),
                ("lpo_id", models.UUIDField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for approval request or rejection"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount requiring approval",
                        max_digits=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval",
                "verbose_name_plural": "Approvals",
                "db_table": "approvals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["approval_type", "status"],
                        name="approvals_approva_2458e7_idx",
                    ),
                    models.Index(fields=["status"], name="approvals_status_658918_idx"),
                    models.Index(
                        fields=["requested_by"], name="approvals_request_40138d_idx"
                    ),
                    models.Index(
                        fields=["approved_by"], name="approvals_approve_5da77c_idx"
                    ),
                ],
            },
        ),
    ]
