# Generated by Django 5.2.6 on 2026-03-17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('VARIATION', 'Variation'), ('PROCUREMENT', 'Procurement'), ('CLAIM', 'Claim'), ('CONTRACT', 'Contract')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_definitions',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_states',
                'ordering': ['workflow', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_transitions',
                'ordering': ['workflow', 'from_state__sort_order', 'to_state__sort_order', 'action'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('VARIATION', 'Variation'), ('PROCUREMENT', 'Procurement'), ('CLAIM', 'Claim'), ('CONTRACT', 'Contract')], db_index=True, max_length=30)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('last_transition_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances_in_state', to='workflows.workflowstate')),
                ('last_transition_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions_performed', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_instances',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from_state', to='workflows.workflowstate')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_history', to='workflows.workflowinstance')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_history_entries', to=settings.AUTH_USER_MODEL)),
                ('to_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to_state', to='workflows.workflowstate')),
            ],
            options={
                'db_table': 'workflow_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['workflow', 'is_initial'], name='workflow_st_workflo_62c341_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['workflow', 'is_terminal'], name='workflow_st_workflo_b4c3ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('workflow', 'name'), name='uniq_workflow_state_name'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['workflow', 'action'], name='workflow_tr_workflo_1b6d75_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['workflow', 'from_state', 'action'], name='workflow_tr_workflo_a11e2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('workflow', 'from_state', 'to_state', 'action'), name='uniq_workflow_transition'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['module', 'current_state'], name='workflow_in_module_9f6dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['module', 'last_transition_at'], name='workflow_in_module_438cfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(fields=('module', 'entity_id'), name='uniq_workflow_instance_entity'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['instance', '-timestamp'], name='workflow_hi_instanc_17ea3d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['action', '-timestamp'], name='workflow_hi_action_50daab_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='uniq_workflow_definition_module_name'),
        ),
    ]
