# Generated by Django 4.2.29 on 2026-03-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_workflow_engine_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflowhistory",
            new_name="workflow_hi_instanc_256f83_idx",
            old_name="workflow_hi_instanc_17ea3d_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowhistory",
            new_name="workflow_hi_action_009449_idx",
            old_name="workflow_hi_action_50daab_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowinstance",
            new_name="workflow_in_module_ee3dcc_idx",
            old_name="workflow_in_module_9f6dd8_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowinstance",
            new_name="workflow_in_module_4f93f2_idx",
            old_name="workflow_in_module_438cfe_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowstate",
            new_name="workflow_st_workflo_095171_idx",
            old_name="workflow_st_workflo_62c341_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowstate",
            new_name="workflow_st_workflo_3288c9_idx",
            old_name="workflow_st_workflo_b4c3ce_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowtransition",
            new_name="workflow_tr_workflo_a981e6_idx",
            old_name="workflow_tr_workflo_1b6d75_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowtransition",
            new_name="workflow_tr_workflo_dff0ee_idx",
            old_name="workflow_tr_workflo_a11e2e_idx",
        ),
    ]
