# Generated by Django 4.2.29 on 2026-03-10 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount received",
                        max_digits=15,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Transaction reference, cheque number, or receipt number",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Payment description or notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_payments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Payment",
                "verbose_name_plural": "Client Payments",
                "db_table": "client_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="ClientReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        help_text="Official receipt number", max_length=50, unique=True
                    ),
                ),
                (
                    "document_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to receipt document file",
                        max_length=500,
                    ),
                ),
                ("issued_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="clients.clientpayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Receipt",
                "verbose_name_plural": "Client Receipts",
                "db_table": "client_receipts",
                "ordering": ["-issued_date"],
                "indexes": [
                    models.Index(
                        fields=["receipt_number"], name="client_rece_receipt_4d46f6_idx"
                    ),
                    models.Index(
                        fields=["issued_date"], name="client_rece_issued__043e47_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="clientpayment",
            index=models.Index(
                fields=["project", "payment_date"],
                name="client_paym_project_a560ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clientpayment",
            index=models.Index(
                fields=["reference_number"], name="client_paym_referen_5b6a8c_idx"
            ),
        ),
    ]
