# Generated by Django 4.2.29 on 2026-03-11 11:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_contract_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total project contract value",
                        max_digits=15,
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total approved expenses to date",
                        max_digits=15,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total client payments received",
                        max_digits=15,
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Revenue minus expenses",
                        max_digits=15,
                    ),
                ),
                (
                    "budget_utilization",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of budget used (expenses / contract_value * 100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999.99),
                        ],
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Profit margin percentage (profit / revenue * 100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(-999.99),
                            django.core.validators.MaxValueValidator(999.99),
                        ],
                    ),
                ),
                (
                    "project_health",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "planned_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="PV - Budgeted cost of work scheduled",
                        max_digits=15,
                    ),
                ),
                (
                    "earned_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="EV - Budgeted cost of work performed (based on valuations)",
                        max_digits=15,
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="AC - Actual expenses incurred",
                        max_digits=15,
                    ),
                ),
                (
                    "cost_performance_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="CPI = EV / AC (>1 is good, <1 is over budget)",
                        max_digits=5,
                    ),
                ),
                (
                    "schedule_performance_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="SPI = EV / PV (>1 is ahead, <1 is behind schedule)",
                        max_digits=5,
                    ),
                ),
                (
                    "days_elapsed",
                    models.IntegerField(
                        default=0, help_text="Days since project start"
                    ),
                ),
                (
                    "days_remaining",
                    models.IntegerField(
                        default=0, help_text="Days until project end date"
                    ),
                ),
                (
                    "schedule_variance_days",
                    models.IntegerField(
                        default=0,
                        help_text="Schedule variance in days (negative = behind)",
                    ),
                ),
                (
                    "is_over_budget",
                    models.BooleanField(
                        default=False,
                        help_text="True if expenses exceed contract value",
                    ),
                ),
                (
                    "is_behind_schedule",
                    models.BooleanField(default=False, help_text="True if SPI < 1.0"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Metrics",
                "verbose_name_plural": "Project Metrics",
                "db_table": "project_metrics",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["project", "last_updated"],
                        name="project_met_project_f14c9d_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="project_met_risk_le_076534_idx"
                    ),
                    models.Index(
                        fields=["project_health"], name="project_met_project_9863b2_idx"
                    ),
                ],
            },
        ),
    ]
