# Generated by Django 4.2.29 on 2026-03-12 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        (
            "authentication",
            "0003_projectaccess_project_projectaccess_user_user_groups_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the permission",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the permission (e.g., 'approve_variations')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the permission", max_length=150
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this permission allows",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("project", "Project Management"),
                            ("financial", "Financial"),
                            ("document", "Document Management"),
                            ("variation", "Variation Orders"),
                            ("claim", "Claims & Valuations"),
                            ("payment", "Payments"),
                            ("approval", "Approvals"),
                            ("report", "Reporting"),
                            ("procurement", "Procurement"),
                            ("subcontract", "Subcontracts"),
                            ("site_operations", "Site Operations"),
                            ("system", "System Administration"),
                        ],
                        db_index=True,
                        help_text="Category this permission belongs to",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this permission is currently active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the permission was created",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the role",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("finance_manager", "Finance Manager"),
                            ("project_manager", "Project Manager"),
                            ("site_engineer", "Site Engineer"),
                            ("consultant", "Consultant"),
                            ("client", "Client"),
                            ("supplier", "Supplier"),
                            ("subcontractor", "Subcontractor"),
                        ],
                        help_text="Unique code for the role",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the role", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of role responsibilities",
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is a system-defined role (cannot be deleted)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this role is currently active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the role was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the role was last updated"
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions assigned to this role",
                        related_name="roles",
                        to="roles.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the user-role assignment",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this role assignment is currently active",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the role was assigned",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the role assignment expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this role assignment",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assigned this role",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization context (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="authentication.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project context (optional, for project-specific roles)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="projects.project",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role assigned to the user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="roles.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User to whom the role is assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_roles",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["code"], name="perm_code_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["category"], name="perm_category_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user", "is_active"], name="ur_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role", "is_active"], name="ur_role_active_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["organization", "is_active"], name="ur_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["project", "is_active"], name="ur_project_active_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role", "organization", "project")},
        ),
    ]
