# Generated by Django 4.2.29 on 2026-03-10 10:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "system_role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("contractor", "Contractor"),
                            ("site_manager", "Site Manager"),
                            ("qs", "Quantity Surveyor"),
                            ("architect", "Architect"),
                            ("client", "Client"),
                            ("staff", "Staff Member"),
                        ],
                        default="client",
                        help_text="System-level role (global permissions)",
                        max_length=20,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, help_text="Job title or position", max_length=100
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last login", null=True
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of consecutive failed login attempts",
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Account locked until this time (for security)",
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Email verification status"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("login_failed", "Login Failed"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("access_granted", "Project Access Granted"),
                            ("access_revoked", "Project Access Revoked"),
                            ("permission_changed", "Permission Changed"),
                            ("password_changed", "Password Changed"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the action",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization name", max_length=255, unique=True
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("contractor", "Contractor Company"),
                            ("consultant", "Consultancy Firm"),
                            ("client", "Client Organization"),
                            ("supplier", "Supplier"),
                            ("other", "Other"),
                        ],
                        default="contractor",
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Business registration number",
                        max_length=100,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, help_text="Tax identification number", max_length=50
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizations/"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Organization is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_role",
                    models.CharField(
                        choices=[
                            ("owner", "Project Owner"),
                            ("manager", "Project Manager"),
                            ("site_manager", "Site Manager"),
                            ("qs", "Quantity Surveyor"),
                            ("architect", "Architect"),
                            ("foreman", "Foreman"),
                            ("engineer", "Engineer"),
                            ("supervisor", "Supervisor"),
                            ("viewer", "Viewer (Read-only)"),
                        ],
                        default="viewer",
                        help_text="Role within this specific project",
                        max_length=20,
                    ),
                ),
                (
                    "can_edit",
                    models.BooleanField(
                        default=False, help_text="Can edit project details"
                    ),
                ),
                (
                    "can_manage_budget",
                    models.BooleanField(
                        default=False, help_text="Can manage project budget"
                    ),
                ),
                (
                    "can_manage_workers",
                    models.BooleanField(
                        default=False, help_text="Can assign and manage workers"
                    ),
                ),
                (
                    "can_approve_documents",
                    models.BooleanField(
                        default=False, help_text="Can approve documents and reports"
                    ),
                ),
                (
                    "can_view_financials",
                    models.BooleanField(
                        default=False, help_text="Can view financial reports"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="User has active access to this project"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Access",
                "verbose_name_plural": "Project Accesses",
                "db_table": "project_access",
                "ordering": ["-assigned_at"],
            },
        ),
    ]
