# Generated by Django 4.2.29 on 2026-03-10 11:03

import apps.authentication.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations/",
                validators=[apps.authentication.validators.validate_organization_logo],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="Organization name",
                max_length=255,
                unique=True,
                validators=[apps.authentication.validators.validate_organization_name],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="Job title or position",
                max_length=100,
                validators=[apps.authentication.validators.validate_job_title],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Contact phone number",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    apps.authentication.validators.validate_phone_number,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                validators=[apps.authentication.validators.validate_profile_picture],
            ),
        ),
    ]
