# Generated by Django 4.2.29 on 2026-03-10 23:39

import apps.authentication.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0002_auditlog_user_organization_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectaccess",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectaccess",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="User's primary organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations/",
                validators=[apps.authentication.validators.validate_organization_logo],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="Organization name",
                max_length=255,
                unique=True,
                validators=[apps.authentication.validators.validate_organization_name],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="Job title or position",
                max_length=100,
                validators=[apps.authentication.validators.validate_job_title],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Contact phone number",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    apps.authentication.validators.validate_phone_number,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                validators=[apps.authentication.validators.validate_profile_picture],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectaccess",
            unique_together={("user", "project")},
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="audit_logs_user_id_e11c73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="audit_logs_action_f48619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address"], name="audit_logs_ip_addr_919cb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="organizatio_name_5cd1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["org_type", "is_active"], name="organizatio_org_typ_257757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectaccess",
            index=models.Index(
                fields=["user", "project", "is_active"],
                name="project_acc_user_id_a817cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectaccess",
            index=models.Index(
                fields=["project", "is_active"], name="project_acc_project_4392e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectaccess",
            index=models.Index(
                fields=["project_role"], name="project_acc_project_a7c2b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["system_role"], name="users_system__2a70e6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "system_role"], name="users_is_acti_b31103_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization"], name="users_organiz_ca9165_idx"
            ),
        ),
    ]
