# Generated by Django 4.2.29 on 2026-03-12 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique template code (e.g., variation_approved)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable template name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description and usage notes"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System Notification"),
                            ("WORKFLOW", "Workflow Event"),
                            ("FINANCIAL", "Financial Alert"),
                            ("DOCUMENT", "Document Activity"),
                            ("REPORT", "Report Generated"),
                            ("DEADLINE", "Deadline Reminder"),
                            ("APPROVAL", "Approval Request"),
                            ("VARIATION", "Variation Update"),
                            ("CONTRACT", "Contract Event"),
                            ("PROCUREMENT", "Procurement Activity"),
                        ],
                        default="SYSTEM",
                        help_text="Type of notification this template generates",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Priority"),
                            ("NORMAL", "Normal Priority"),
                            ("HIGH", "High Priority"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        help_text="Default priority for notifications from this template",
                        max_length=10,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Title template (supports variables: {var_name})",
                        max_length=200,
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Message template (supports variables: {var_name})"
                    ),
                ),
                (
                    "email_subject_template",
                    models.CharField(
                        blank=True,
                        help_text="Email subject template (if different from title)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "email_body_template",
                    models.TextField(
                        blank=True,
                        help_text="Email body template (HTML supported)",
                        null=True,
                    ),
                ),
                (
                    "sms_template",
                    models.CharField(
                        blank=True,
                        help_text="SMS template (max 160 chars)",
                        max_length=160,
                        null=True,
                    ),
                ),
                (
                    "action_url_template",
                    models.CharField(
                        blank=True,
                        help_text="Action URL template (e.g., /projects/{project_id}/)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True,
                        help_text="Action button label (e.g., View Project)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of required template variables (e.g., ["user_name", "amount"])',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, help_text="Receive email notifications"
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, help_text="Receive in-app notifications"
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=False, help_text="Receive SMS notifications"
                    ),
                ),
                (
                    "system_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive system notifications"
                    ),
                ),
                (
                    "workflow_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive workflow event notifications"
                    ),
                ),
                (
                    "financial_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive financial alert notifications"
                    ),
                ),
                (
                    "document_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive document activity notifications",
                    ),
                ),
                (
                    "report_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive report generation notifications",
                    ),
                ),
                (
                    "deadline_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive deadline reminder notifications",
                    ),
                ),
                (
                    "approval_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive approval request notifications"
                    ),
                ),
                (
                    "digest_enabled",
                    models.BooleanField(
                        default=False, help_text="Group notifications into daily digest"
                    ),
                ),
                (
                    "digest_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time to send daily digest (e.g., 09:00)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable quiet hours (no notifications during specified time)",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start of quiet hours (e.g., 22:00)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="End of quiet hours (e.g., 08:00)",
                        null=True,
                    ),
                ),
                (
                    "sms_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for SMS notifications",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Batch name/description", max_length=200
                    ),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of recipients"
                    ),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of notifications sent"
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of failed notifications"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Batch processing status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the batch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template used for batch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Batch",
                "verbose_name_plural": "Notification Batches",
                "db_table": "notification_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title/subject", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Notification message body")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System Notification"),
                            ("WORKFLOW", "Workflow Event"),
                            ("FINANCIAL", "Financial Alert"),
                            ("DOCUMENT", "Document Activity"),
                            ("REPORT", "Report Generated"),
                            ("DEADLINE", "Deadline Reminder"),
                            ("APPROVAL", "Approval Request"),
                            ("VARIATION", "Variation Update"),
                            ("CONTRACT", "Contract Event"),
                            ("PROCUREMENT", "Procurement Activity"),
                        ],
                        default="SYSTEM",
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Priority"),
                            ("NORMAL", "Normal Priority"),
                            ("HIGH", "High Priority"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        help_text="Notification priority level",
                        max_length=10,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of related entity",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether notification has been read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was read", null=True
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False, help_text="Whether email was sent"
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When email was sent", null=True
                    ),
                ),
                (
                    "sms_sent",
                    models.BooleanField(
                        default=False, help_text="Whether SMS was sent"
                    ),
                ),
                (
                    "sms_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When SMS was sent", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional notification data (action URLs, entity details, etc.)",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate to when notification is clicked",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True,
                        help_text="Label for action button",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When notification was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When notification was last updated"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When notification expires (for cleanup)",
                        null=True,
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of related entity",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Recipient of the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_19df93_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="notificatio_entity__b44840_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="notificatio_expires_66996e_idx"
                    ),
                ],
            },
        ),
    ]
